import '@/src/app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Heading from '@/src/components/heading';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
   return (
      <html lang="en">
         <body className={inter.className}>
            <Heading />
            <main className="w-full px-4 py-10 sm:px-6 lg:px-8">{children}</main>
         </body>
      </html>
   );
}
